# Generated by Django 4.2.3 on 2023-07-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IHA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marka", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("agirlik", models.FloatField()),
                ("kategori", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Kiralama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih_ve_saat_araliklari", models.CharField(max_length=200)),
                ("kiralayan_uye", models.CharField(max_length=100)),
                (
                    "iha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iha_kiralama.iha",
                    ),
                ),
            ],
        ),
    ]
