# Generated by Django 4.2.3 on 2023-07-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iha_kiralama", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kiralama",
            name="tarih_ve_saat_araliklari",
            field=models.DateField(),
        ),
    ]
