# Generated by Django 4.2.3 on 2023-07-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iha_kiralama", "0002_alter_kiralama_tarih_ve_saat_araliklari"),
    ]

    operations = [
        migrations.AddField(
            model_name="kiralama",
            name="teslim_tarihi",
            field=models.DateField(default="1970-01-01"),
            preserve_default=False,
        ),
    ]
